### ISSUE TITLE
Provide configuration for webservices.log

### ISSUE THREAD

**Issue by adibaba** [projekt-opal/web-service#3]
Users should be free to set the path to `webservices.log`. A configuration setting for the file is required. The path should be set similar to the properties in `application.yml`.

The path for `webservices.log` currentliy is set in `logback-spring.xml`.

**Comment by adibaba** [comment]
Also these should become variables:

- `logback-spring.xml` `fileNamePattern`
- `logback-spring.xml` `totalSizeCap`

(found in `developer` branch)

**Comment by mnafshin** [comment]
OK.
All in all, as in the production version there would be a docker container, so every user can change the logback-spring.xml file completely, or else provide the path as a volume.
