### ISSUE TITLE
pom.xml configuration

### ISSUE THREAD

**Issue by adibaba** [projekt-opal/web-service#6]
- `<groupId>de.upb.cs.dice</groupId>` -> `<groupId>org.dice-research.opal</groupId>`
- `<artifactId>opal-webservices</artifactId>` -> `<artifactId>ui-webservices</artifactId>`
- `<name>opal-webservices</name>` -> `OPAL UI webservices`
- `<description>Demo project for Spring Boot</description>` -> `<description>Provider for required webservices in OPAL Web User Interface (web-ui)</description>`

**Comment by mnafshin** [comment]
I think it is not restricted to only the UI, every one can call them. 
<artifactId>opal-webservices</artifactId> -> <artifactId>ui-webservices</artifactId>
<name>opal-webservices</name> -> OPAL UI webservices

**Comment by adibaba** [comment]
okay.
for the artefactId, 'opal' is not needed. we can use 'webservices' or something similar
for the name, it could be 'OPAL webservices'

**Comment by mnafshin** [comment]
please rename the project directory from "opal-webservices" to "webservices"

**Comment by mnafshin** [comment]
The new parameters are:
```
<groupId>org.dice-research.opal</groupId>
    <artifactId>webservice</artifactId>
    <version>1.0.0.0</version>
    <name>webservice</name>
    <description>Provider for required webservices in OPAL Web User Interface (web-ui)</description>
```
